on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master]

name: R-CMD-check-special

jobs:
  sanitizers-and-valgrind:
    runs-on: ubuntu-latest
    name: ${{ matrix.config.name }}
    container:
      image: ${{ matrix.config.container }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - { label: "clang-asan",
              name: "clang-asan",
              container: "ghcr.io/r-hub/containers/clang-asan:latest"}
          - { label: "gcc-asan",
              name: "gcc-asan",
              container: "ghcr.io/r-hub/containers/gcc-asan:latest"}
          - { label: "valgrind",
              name: "valgrind",
              container: "ghcr.io/r-hub/containers/valgrind:latest"}

    env:
      MAKEFLAGS: -j4
    steps:
      - uses: r-hub/actions/checkout@main
        with:
          submodules: true
      - uses: r-hub/actions/platform-info@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          job-config: ${{ toJson(matrix.config) }}
      - uses: r-hub/actions/setup-deps@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          job-config: ${{ toJson(matrix.config) }}
      - uses: r-hub/actions/run-check@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          job-config: ${{ toJson(matrix.config) }}
