# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'inst/bundle/**'
permissions:
  contents: write

name: Update-Bundles

jobs:
  Update-Bundles:
    runs-on: 'ubuntu-latest'
    name: Updating JS Bundles

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      MAKEFLAGS: -j4
      ESPRIMA_VERSION: ""
      SASS_VERSION: ""
      TERSER_VERSION: ""
      TYPESCRIPT_VERSION: ""


    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - name: Set up Node.js
        uses: actions/setup-node@v6

      - name: Install dependencies and record versions
        working-directory: ./inst/bundle
        run: |
          npm install
          echo "ESPRIMA_VERSION=$(npm list esprima --depth=0 | grep esprima | cut -d@ -f2)" >> $GITHUB_ENV
          echo "SASS_VERSION=$(npm list sass --depth=0 | grep sass | cut -d@ -f2)" >> $GITHUB_ENV
          echo "TERSER_VERSION=$(npm list terser --depth=0 | grep terser | cut -d@ -f2)" >> $GITHUB_ENV
          echo "TYPESCRIPT_VERSION=$(npm list typescript --depth=0 | grep typescript | cut -d@ -f2)" >> $GITHUB_ENV

      - name: Update bundle files
        working-directory: ./inst/bundle
        run: |
          rm ../js/esprima*.js || true
          rm ../js/sass*.js || true
          rm ../js/terser*.js || true
          rm ../js/typescript*.js || true

          npx rollup esprima.js --file ../js/esprima.${{ env.ESPRIMA_VERSION }}.js --format iife --plugin 'node-resolve={browser:true}' --plugin commonjs --name "esprima"
          npx rollup sass.js --file ../js/sass.${{ env.SASS_VERSION }}.js --format iife --plugin 'node-resolve={browser:true}' --plugin commonjs --name "sass"
          npx rollup terser.js --file ../js/terser.${{ env.TERSER_VERSION }}.js --format iife --plugin 'node-resolve={browser:true}' --plugin commonjs --name "terser"
          npx rollup typescript.js --file ../js/typescript.${{ env.TYPESCRIPT_VERSION }}.js --format iife --plugin 'node-resolve={browser:true}' --plugin commonjs --name "ts"

      - name: Update version numbers in R files
        run: |
          sed -i "s/ESPRIMA_VERSION <- \".*\"/ESPRIMA_VERSION <- \"${{ env.ESPRIMA_VERSION }}\"/" R/versions.R
          sed -i "s/SASS_VERSION <- \".*\"/SASS_VERSION <- \"${{ env.SASS_VERSION }}\"/" R/versions.R
          sed -i "s/TERSER_VERSION <- \".*\"/TERSER_VERSION <- \"${{ env.TERSER_VERSION }}\"/" R/versions.R
          sed -i "s/TYPESCRIPT_VERSION <- \".*\"/TYPESCRIPT_VERSION <- \"${{ env.TYPESCRIPT_VERSION }}\"/" R/versions.R

      - name: Commit and push changes
        run: |
          git pull
            if [[ -n "$(git status -s)" ]]; then
              git config --global user.name "github-actions[bot]"
              git config --global user.email "github-actions[bot]@users.noreply.github.com"
              git add ./inst/js ./R/versions.R
              git commit -m "Update JS bundles to latest versions" || echo "No changes to commit"
            git push
          else
            echo "No changes to commit."
          fi
